[project]
name = "maan"
languages = ["C", "CXX"]

[variables]
CMAKE_EXPORT_COMPILE_COMMANDS=true

[fetch-content]
Catch2 = { git = "https://github.com/catchorg/Catch2", tag = "v3.3.2" }
# fmt = { git = "https://github.com/fmtlib/fmt/", tag = "9.1.0" }

[target.maan]
type = "interface"
sources = ["maan/include/*.hpp", "maan/include/maan/*.hpp"]
compile-features = ["cxx_std_23"]
include-directories = ["luajit/include", "maan/include"]
link-libraries = ["lua51"]
x64.link-directories = ["luajit/x64/lib"]
x32.link-directories = ["luajit/x86/lib"]

[target.tests]
type = "executable"
sources = ["tests/*.cpp"]
link-libraries = ["Catch2::Catch2WithMain", "maan"]
compile-features = ["cxx_std_23"]
cmake-after = """
list(APPEND CMAKE_MODULE_PATH ${catch2_SOURCE_DIR}/extras)
include(CTest)
include(Catch)
catch_discover_tests(tests)
"""
