[project]
name = "maan"
languages = ["C", "CXX"]

[fetch-content]
Catch2 = { git = "https://github.com/catchorg/Catch2", tag = "v3.5.4" }

[target.maan]
type = "interface"
sources = ["src/include/*.hpp", "src/include/maan/*.hpp"]
compile-features = ["cxx_std_23"]
include-directories = ["luajit/include", "src/include"]
link-libraries = ["lua51"]
x64.link-directories = ["luajit/x64/lib"]
x32.link-directories = ["luajit/x32/lib"]
arm64.link-directories = ["luajit/arm64/lib"]

[target.tests]
type = "executable"
sources = ["tests/*.cpp"]
link-libraries = ["Catch2::Catch2WithMain", "maan"]
compile-features = ["cxx_std_23"]
cmake-after = """
list(APPEND CMAKE_MODULE_PATH ${catch2_SOURCE_DIR}/extras)
include(CTest)
include(Catch)
catch_discover_tests(tests)
"""
